# Server Configuration
server.port=9191

# OracleDB connection settings
#192.192.192.193:1521/pdbdev.mfi.com
spring.datasource.url=jdbc:oracle:thin:@//192.192.192.193:1521/pdbdev.mfi.com
spring.datasource.username=gkasdb_live
spring.datasource.password=U#$GL2021
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.use-new-id-generator-mappings=false

# DDL OPERATION
spring.jpa.hibernate.ddl-auto=update

origins = http://103.26.136.30,http://localhost:8081

accounts = http://103.26.136.30:9393/api/v1/
auto-voucher=vouchers/auto
get-auto-voucher-alias=auto-vouchers/by-module/

# LOGGING
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MULTIPART FILE Configuration
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties

file.upload-dir=./uploads

## Keycloak properties
keycloak.enabled=true
keycloak.realm=GK_LIVE
keycloak.auth-server-url=http://103.26.136.30:8080/auth
keycloak.resource=gk-health-api
keycloak.bearer-only=true
keycloak.cors=true